title: Portafolio de Ainhoa Manchado
author: Ainhoa Manchado
email: 98ainhoam@opendeusto.es
description: > # this means to ignore newlines until "baseurl:"
  Mi nombre es Ainhoa Manchado y este es el portafolio personal donde podrán leerse los resumenes de las lecturas que he hecho para las reuniones de expertos.
# social links
# twitter_username: tu-usuario-twitter 
github_username:  Ainhoa-M-github
show_excerpts: true 

theme: minima
