title: Portafolio de Ainhoa Manchado
author: Ainhoa Manchado
email: 98ainhoam@opendeusto.es
description: > # this means to ignore newlines until "baseurl:"
  No sé que poner asi que pongo esto
# social links
# twitter_username: tu-usuario-twitter 
github_username:  Ainhoa-M-github
show_excerpts: true 

theme: minima
